trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md

pool:
  vmImage: windows-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
  displayName: 'Using Python'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install python packages'

- script: |
    pyinstaller streamlit_runner.spec
  displayName: 'Build with PyInstaller'

- task: CopyFiles@2
  inputs:
    contents: |
      DashboardPro.cs
      dashboard.py
    targetFolder: $(Build.ArtifactStagingDirectory)
  displayName: 'Stage scritps'

- task: CopyFiles@2
  inputs:
    sourceFolder: dist
    targetFolder: $(Build.ArtifactStagingDirectory)
  displayName: 'Stage build'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: 'DashboardPro $(Build.BuildNumber)'