name: BeamDashBoardPro Python Application Release

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Release version (build date/tag name)'
        required: true
  #     default: 'v20yy.M.D.#'
        default: $(date +'%Y.%m.%d')'.BuildX'
  # push:
  #   tags:
  #     - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  #   branches: [ main ]
  #   paths-ignore:
  #     - 'README.md'
  # pull_request:
  #   branches: [ main ]

env:
  RELEASE_NAME: ${{ github.event.repository.name }}-${{ github.event.inputs.version_tag }}

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Make Expiration
      run: |
        python make_expiration.py

    - name: Build with PyInstaller
      run: |
        pyinstaller streamlit_runner.spec
        
    # - name: Stage build
    #   run: |
    #     cp -r dist "${{ runner.temp }}/dist"
        
    - name: Stage scripts
      run: |
        cp DashboardPro.cs "dist/DashboardPro.cs"
        cp dashboard.py "dist/dashboard.py"

    - name: Zip
      run: |
        Compress-Archive `
          -Path "dist/*" `
          -DestinationPath "${{ env.RELEASE_NAME }}.zip"
    
    - name: Create Release
      uses: softprops/action-gh-release@v0.1.13
      with:
        name: ${{ env.RELEASE_NAME }}
        tag_name: ${{ github.event.inputs.version_tag }}
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: true
        prerelease: false
        body: |
          This is the official release of **`${{ github.event.repository.name }}`** `${{ github.event.inputs.version_tag }}`.
          The .zip file contains a portable "compiled" python executable created with PyInstaller along with an ESAPI single file script launcher (.cs).
          For use on Eclipse versions 16 and up.
          This software is valid until 365 post release.
        files: ${{ env.RELEASE_NAME }}.zip
#    - name: Upload artifact
#      uses: actions/upload-artifact@v2
#      with:
#        name: DashboardPro${{ github.ref_name }}
#        path: ${{ runner.temp }}/dist/*
